/*
 * ytelapiv3_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package shortcode_pkg

import "ytelapiv3_lib/configuration_pkg"

/*
 * Interface for the SHORTCODE_IMPL
 */
type SHORTCODE interface {
    CreateListShortcodes (*string, *string, *string) (string, error)

    CreateViewSMS (string) (string, error)

    CreateViewSMS (string) (string, error)

    CreateListSMS (*string, *string, *string, *int64, *int64) (string, error)

    CreateSendSMS (int64, float64, string, *string, *string) (string, error)

    CreateListInboundSMS (*int64, *int64, *string, *string, *string) (string, error)

    UpdateShortcode (string, *string, *string, *string, *string, *string) (string, error)
}

/*
 * Factory for the SHORTCODE interaface returning SHORTCODE_IMPL
 */
func NewSHORTCODE(config configuration_pkg.CONFIGURATION) *SHORTCODE_IMPL {
    client := new(SHORTCODE_IMPL)
    client.config = config
    return client
}