/*
 * ytelapiv3_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package address_pkg

import "ytelapiv3_lib/configuration_pkg"

/*
 * Interface for the ADDRESS_IMPL
 */
type ADDRESS interface {
    CreateDeleteAddress (string) (string, error)

    CreateVerifyAddress (string) (string, error)

    CreateViewAddress (string) (string, error)

    CreateListAddresses (*int64, *int64, *string, *string) (string, error)

    CreateAddress (string, string, string, string, string, string, *string, *string, *string) (string, error)
}

/*
 * Factory for the ADDRESS interaface returning ADDRESS_IMPL
 */
func NewADDRESS(config configuration_pkg.CONFIGURATION) *ADDRESS_IMPL {
    client := new(ADDRESS_IMPL)
    client.config = config
    return client
}