/*
 * ytelapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

package YtelAPIClient

import(
	"ytelapi_lib/configuration_pkg"
	"ytelapi_lib/shortcode_pkg"
	"ytelapi_lib/areamail_pkg"
	"ytelapi_lib/postcard_pkg"
	"ytelapi_lib/letter_pkg"
	"ytelapi_lib/call_pkg"
	"ytelapi_lib/phone number_pkg"
	"ytelapi_lib/sms_pkg"
	"ytelapi_lib/sharedshortcode_pkg"
	"ytelapi_lib/conference_pkg"
	"ytelapi_lib/carrier_pkg"
	"ytelapi_lib/email_pkg"
	"ytelapi_lib/account_pkg"
	"ytelapi_lib/sub account_pkg"
	"ytelapi_lib/address_pkg"
	"ytelapi_lib/recording_pkg"
	"ytelapi_lib/transcription_pkg"
	"ytelapi_lib/usage_pkg"
)


/*
 * Interface for the YTELAPI_IMPL
 */
type YTELAPI interface {
     ShortCode()             shortcode_pkg.SHORTCODE
     AreaMail()              areamail_pkg.AREAMAIL
     PostCard()              postcard_pkg.POSTCARD
     Letter()                letter_pkg.LETTER
     Call()                  call_pkg.CALL
     PhoneNumber()          phone number_pkg.PHONE NUMBER
     SMS()                   sms_pkg.SMS
     SharedShortCode()       sharedshortcode_pkg.SHAREDSHORTCODE
     Conference()            conference_pkg.CONFERENCE
     Carrier()               carrier_pkg.CARRIER
     Email()                 email_pkg.EMAIL
     Account()               account_pkg.ACCOUNT
     SubAccount()           sub account_pkg.SUB ACCOUNT
     Address()               address_pkg.ADDRESS
     Recording()             recording_pkg.RECORDING
     Transcription()         transcription_pkg.TRANSCRIPTION
     Usage()                 usage_pkg.USAGE
     Configuration()         configuration_pkg.CONFIGURATION
}

/*
 * Factory for the YTELAPI interaface returning YTELAPI_IMPL
 */
func NewYTELAPI(basicAuthUserName string, basicAuthPassword string) YTELAPI {
    ytelAPIClient := new(YTELAPI_IMPL)
    ytelAPIClient.config = configuration_pkg.NewCONFIGURATION()
    ytelAPIClient.config.SetBasicAuthUserName(basicAuthUserName)
    ytelAPIClient.config.SetBasicAuthPassword(basicAuthPassword)
    return ytelAPIClient
}
