/*
 * ytelapiv3_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package subaccount_pkg

import "ytelapiv3_lib/models_pkg"
import "ytelapiv3_lib/configuration_pkg"

/*
 * Interface for the SUBACCOUNT_IMPL
 */
type SUBACCOUNT interface {
    CreateToggleSubaccountStatus (string, models_pkg.MActivateEnum) (string, error)

    CreateDeleteSubaccount (string, models_pkg.MergeNumberEnum) (string, error)

    CreateSubaccount (string, string, string, string, string) (string, error)
}

/*
 * Factory for the SUBACCOUNT interaface returning SUBACCOUNT_IMPL
 */
func NewSUBACCOUNT(config configuration_pkg.CONFIGURATION) *SUBACCOUNT_IMPL {
    client := new(SUBACCOUNT_IMPL)
    client.config = config
    return client
}