/*
 * ytelapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

package call_pkg

import "ytelapi_lib/configuration_pkg"

/*
 * Interface for the CALL_IMPL
 */
type CALL interface {
    CreateCallsViewcalldetail (string) (string, error)

    CreateCallsViewcalls (string) (string, error)

    CreateCallsSenddigits (*CreateCallsSenddigitsInput) (string, error)

    CreateCallsMakervm (*CreateCallsMakervmInput) (string, error)

    CreateCallsListcalls (*CreateCallsListcallsInput) (string, error)

    CreateCallsInterruptcalls (*CreateCallsInterruptcallsInput) (string, error)

    CreateCallsRecordcalls (*CreateCallsRecordcallsInput) (string, error)

    CreateCallsPlayaudios (*CreateCallsPlayaudiosInput) (string, error)

    CreateCallsVoiceeffect (*CreateCallsVoiceeffectInput) (string, error)

    CreateCallsGroupcall (*CreateCallsGroupcallInput) (string, error)

    CreateCallsMakecall (*CreateCallsMakecallInput) (string, error)
}

/*
 * Factory for the CALL interaface returning CALL_IMPL
 */
func NewCALL(config configuration_pkg.CONFIGURATION) *CALL_IMPL {
    client := new(CALL_IMPL)
    client.config = config
    return client
}