/*
 * ytelapiv3_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package letter_pkg

import "ytelapiv3_lib/configuration_pkg"

/*
 * Interface for the LETTER_IMPL
 */
type LETTER interface {
    CreateDeleteLetter (string) (string, error)

    CreateViewLetter (string) (string, error)

    CreateLetter (string, string, string, string, string, *string, *string, *string, *string, *string) (string, error)

    CreateListLetters (*int64, *int64, *string, *string) (string, error)
}

/*
 * Factory for the LETTER interaface returning LETTER_IMPL
 */
func NewLETTER(config configuration_pkg.CONFIGURATION) *LETTER_IMPL {
    client := new(LETTER_IMPL)
    client.config = config
    return client
}