/*
 * ytelapiv3_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package call_pkg

import "ytelapiv3_lib/models_pkg"
import "ytelapiv3_lib/configuration_pkg"

/*
 * Interface for the CALL_IMPL
 */
type CALL interface {
    CreateViewCall1 (string) (string, error)

    CreateViewCall (string) (string, error)

    CreatePlayDTMF (string, string, models_pkg.PlayDtmfDirectionEnum) (string, error)

    CreateMakeCall (string, string, string, *string, *string, *string, *string, *string, *string, *string, *int64, *string, *bool, *bool, *string, *string, *bool, *string, models_pkg.IfMachineEnum, *string, *string, *bool, *string) (string, error)

    CreatePlayAudio (string, string, string, *int64, models_pkg.DirectionEnum, *bool) (string, error)

    CreateRecordCall (string, bool, models_pkg.Direction4Enum, *int64, *string, models_pkg.FileformatEnum) (string, error)

    CreateVoiceEffect (string, models_pkg.AudioDirectionEnum, *float64, *float64, *float64, *float64, *float64) (string, error)

    CreateInterruptCall (string, *string, *string, models_pkg.StatusEnum) (string, error)

    CreateListCalls (*int64, *int64, *string, *string, *string) (string, error)

    CreateSendRVM (string, string, string, string, *string, *string, *string) (string, error)

    CreateGroupCall (string, string, string, string, models_pkg.GroupConfirmFileEnum, *string, *string, *string, *string, *string, *string, *string, *int64, *string, *string, *bool, *string, *string, *bool, *string) (string, error)
}

/*
 * Factory for the CALL interaface returning CALL_IMPL
 */
func NewCALL(config configuration_pkg.CONFIGURATION) *CALL_IMPL {
    client := new(CALL_IMPL)
    client.config = config
    return client
}