/*
 * ytelapiv3_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package models_pkg

import(
    "encoding/json"
)

/**
 * Type definition for AudioDirection29Enum enum
 */
type AudioDirection29Enum int

/**
 * Value collection for AudioDirection29Enum enum
 */
const (
    AudioDirection29_IN AudioDirection29Enum = 1 + iota
    AudioDirection29_OUT
)

func (r AudioDirection29Enum) MarshalJSON() ([]byte, error) { 
    s := AudioDirection29EnumToValue(r)
    return json.Marshal(s) 
} 

func (r *AudioDirection29Enum) UnmarshalJSON(data []byte) error { 
    var s string 
    json.Unmarshal(data, &s)
    v :=  AudioDirection29EnumFromValue(s)
    *r = v 
    return nil 
 } 


/**
 * Converts AudioDirection29Enum to its string representation
 */
func AudioDirection29EnumToValue(audioDirection29Enum AudioDirection29Enum) string {
    switch audioDirection29Enum {
        case AudioDirection29_IN:
    		return "IN"		
        case AudioDirection29_OUT:
    		return "OUT"		
        default:
        	return "IN"
    }
}

/**
 * Converts AudioDirection29Enum Array to its string Array representation
*/
func AudioDirection29EnumArrayToValue(audioDirection29Enum []AudioDirection29Enum) []string {
    convArray := make([]string,len( audioDirection29Enum))
    for i:=0; i<len(audioDirection29Enum);i++ {
        convArray[i] = AudioDirection29EnumToValue(audioDirection29Enum[i])
    }
    return convArray
}


/**
 * Converts given value to its enum representation
 */
func AudioDirection29EnumFromValue(value string) AudioDirection29Enum {
    switch value {
        case "IN":
            return AudioDirection29_IN
        case "OUT":
            return AudioDirection29_OUT
        default:
            return AudioDirection29_IN
    }
}
