/*
 * ytelapiv3_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package models_pkg

import(
    "encoding/json"
)

/**
 * Type definition for Direction4Enum enum
 */
type Direction4Enum int

/**
 * Value collection for Direction4Enum enum
 */
const (
    Direction4_IN Direction4Enum = 1 + iota
    Direction4_OUT
    Direction4_BOTH
)

func (r Direction4Enum) MarshalJSON() ([]byte, error) { 
    s := Direction4EnumToValue(r)
    return json.Marshal(s) 
} 

func (r *Direction4Enum) UnmarshalJSON(data []byte) error { 
    var s string 
    json.Unmarshal(data, &s)
    v :=  Direction4EnumFromValue(s)
    *r = v 
    return nil 
 } 


/**
 * Converts Direction4Enum to its string representation
 */
func Direction4EnumToValue(direction4Enum Direction4Enum) string {
    switch direction4Enum {
        case Direction4_IN:
    		return "in"		
        case Direction4_OUT:
    		return "out"		
        case Direction4_BOTH:
    		return "both"		
        default:
        	return "in"
    }
}

/**
 * Converts Direction4Enum Array to its string Array representation
*/
func Direction4EnumArrayToValue(direction4Enum []Direction4Enum) []string {
    convArray := make([]string,len( direction4Enum))
    for i:=0; i<len(direction4Enum);i++ {
        convArray[i] = Direction4EnumToValue(direction4Enum[i])
    }
    return convArray
}


/**
 * Converts given value to its enum representation
 */
func Direction4EnumFromValue(value string) Direction4Enum {
    switch value {
        case "in":
            return Direction4_IN
        case "out":
            return Direction4_OUT
        case "both":
            return Direction4_BOTH
        default:
            return Direction4_IN
    }
}
