/*
 * ytelapiv3_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package models_pkg

import(
    "encoding/json"
)

/**
 * Type definition for Fileformat37Enum enum
 */
type Fileformat37Enum int

/**
 * Value collection for Fileformat37Enum enum
 */
const (
    Fileformat37_MP3 Fileformat37Enum = 1 + iota
    Fileformat37_WAV
)

func (r Fileformat37Enum) MarshalJSON() ([]byte, error) { 
    s := Fileformat37EnumToValue(r)
    return json.Marshal(s) 
} 

func (r *Fileformat37Enum) UnmarshalJSON(data []byte) error { 
    var s string 
    json.Unmarshal(data, &s)
    v :=  Fileformat37EnumFromValue(s)
    *r = v 
    return nil 
 } 


/**
 * Converts Fileformat37Enum to its string representation
 */
func Fileformat37EnumToValue(fileformat37Enum Fileformat37Enum) string {
    switch fileformat37Enum {
        case Fileformat37_MP3:
    		return "mp3"		
        case Fileformat37_WAV:
    		return "wav"		
        default:
        	return "mp3"
    }
}

/**
 * Converts Fileformat37Enum Array to its string Array representation
*/
func Fileformat37EnumArrayToValue(fileformat37Enum []Fileformat37Enum) []string {
    convArray := make([]string,len( fileformat37Enum))
    for i:=0; i<len(fileformat37Enum);i++ {
        convArray[i] = Fileformat37EnumToValue(fileformat37Enum[i])
    }
    return convArray
}


/**
 * Converts given value to its enum representation
 */
func Fileformat37EnumFromValue(value string) Fileformat37Enum {
    switch value {
        case "mp3":
            return Fileformat37_MP3
        case "wav":
            return Fileformat37_WAV
        default:
            return Fileformat37_MP3
    }
}
