/*
 * ytelapiv3_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package models_pkg

import(
    "encoding/json"
)

/**
 * Type definition for MergeNumber40Enum enum
 */
type MergeNumber40Enum int

/**
 * Value collection for MergeNumber40Enum enum
 */
const (
    MergeNumber40_DELETE MergeNumber40Enum = 0
    MergeNumber40_MERGE = 1
)

func (r MergeNumber40Enum) MarshalJSON() ([]byte, error) { 
    s := MergeNumber40EnumToValue(r)
    return json.Marshal(s) 
} 

func (r *MergeNumber40Enum) UnmarshalJSON(data []byte) error { 
    var s int 
    json.Unmarshal(data, &s)
    v :=  MergeNumber40EnumFromValue(s)
    *r = v 
    return nil 
 } 


/**
 * Converts MergeNumber40Enum to its int representation
 */
func MergeNumber40EnumToValue(mergeNumber40Enum MergeNumber40Enum) int {
    switch mergeNumber40Enum {
        case MergeNumber40_DELETE:
    		return 0		
        case MergeNumber40_MERGE:
    		return 1		
        default:
        	return 0
    }
}

/**
 * Converts MergeNumber40Enum Array to its string Array representation
*/
func MergeNumber40EnumArrayToValue(mergeNumber40Enum []MergeNumber40Enum) []int {
    convArray := make([]int,len( mergeNumber40Enum))
    for i:=0; i<len(mergeNumber40Enum);i++ {
        convArray[i] = MergeNumber40EnumToValue(mergeNumber40Enum[i])
    }
    return convArray
}


/**
 * Converts given value to its enum representation
 */
func MergeNumber40EnumFromValue(value int) MergeNumber40Enum {
    switch value {
        case 0:
            return MergeNumber40_DELETE
        case 1:
            return MergeNumber40_MERGE
        default:
            return MergeNumber40_DELETE
    }
}
