/*
 * ytelapiv3_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package models_pkg

import(
    "encoding/json"
)

/**
 * Type definition for PlayDtmfDirection38Enum enum
 */
type PlayDtmfDirection38Enum int

/**
 * Value collection for PlayDtmfDirection38Enum enum
 */
const (
    PlayDtmfDirection38_IN PlayDtmfDirection38Enum = 1 + iota
    PlayDtmfDirection38_OUT
    PlayDtmfDirection38_BOTH
)

func (r PlayDtmfDirection38Enum) MarshalJSON() ([]byte, error) { 
    s := PlayDtmfDirection38EnumToValue(r)
    return json.Marshal(s) 
} 

func (r *PlayDtmfDirection38Enum) UnmarshalJSON(data []byte) error { 
    var s string 
    json.Unmarshal(data, &s)
    v :=  PlayDtmfDirection38EnumFromValue(s)
    *r = v 
    return nil 
 } 


/**
 * Converts PlayDtmfDirection38Enum to its string representation
 */
func PlayDtmfDirection38EnumToValue(playDtmfDirection38Enum PlayDtmfDirection38Enum) string {
    switch playDtmfDirection38Enum {
        case PlayDtmfDirection38_IN:
    		return "IN"		
        case PlayDtmfDirection38_OUT:
    		return "OUT"		
        case PlayDtmfDirection38_BOTH:
    		return "BOTH"		
        default:
        	return "IN"
    }
}

/**
 * Converts PlayDtmfDirection38Enum Array to its string Array representation
*/
func PlayDtmfDirection38EnumArrayToValue(playDtmfDirection38Enum []PlayDtmfDirection38Enum) []string {
    convArray := make([]string,len( playDtmfDirection38Enum))
    for i:=0; i<len(playDtmfDirection38Enum);i++ {
        convArray[i] = PlayDtmfDirection38EnumToValue(playDtmfDirection38Enum[i])
    }
    return convArray
}


/**
 * Converts given value to its enum representation
 */
func PlayDtmfDirection38EnumFromValue(value string) PlayDtmfDirection38Enum {
    switch value {
        case "IN":
            return PlayDtmfDirection38_IN
        case "OUT":
            return PlayDtmfDirection38_OUT
        case "BOTH":
            return PlayDtmfDirection38_BOTH
        default:
            return PlayDtmfDirection38_IN
    }
}
