/*
 * ytelapiv3_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package models_pkg

import(
    "encoding/json"
)

/**
 * Type definition for ProductCode30Enum enum
 */
type ProductCode30Enum int

/**
 * Value collection for ProductCode30Enum enum
 */
const (
    ProductCode30_ALL ProductCode30Enum = 0
    ProductCode30_ENUM_1 = 1
    ProductCode30_ENUM_2 = 2
    ProductCode30_ENUM_3 = 3
    ProductCode30_ENUM_4 = 4
    ProductCode30_TRANSCRIPTION = 5
    ProductCode30_EMAIL = 6
    ProductCode30_CONFERENCE = 7
    ProductCode30_CARRIER = 8
    ProductCode30_ENUM_9 = 9
    ProductCode30_ENUM_10 = 10
    ProductCode30_ENUM_11 = 11
    ProductCode30_ENUM_12 = 12
    ProductCode30_ENUM_13 = 13
)

func (r ProductCode30Enum) MarshalJSON() ([]byte, error) { 
    s := ProductCode30EnumToValue(r)
    return json.Marshal(s) 
} 

func (r *ProductCode30Enum) UnmarshalJSON(data []byte) error { 
    var s int 
    json.Unmarshal(data, &s)
    v :=  ProductCode30EnumFromValue(s)
    *r = v 
    return nil 
 } 


/**
 * Converts ProductCode30Enum to its int representation
 */
func ProductCode30EnumToValue(productCode30Enum ProductCode30Enum) int {
    switch productCode30Enum {
        case ProductCode30_ALL:
    		return 0		
        case ProductCode30_ENUM_1:
    		return 1		
        case ProductCode30_ENUM_2:
    		return 2		
        case ProductCode30_ENUM_3:
    		return 3		
        case ProductCode30_ENUM_4:
    		return 4		
        case ProductCode30_TRANSCRIPTION:
    		return 5		
        case ProductCode30_EMAIL:
    		return 6		
        case ProductCode30_CONFERENCE:
    		return 7		
        case ProductCode30_CARRIER:
    		return 8		
        case ProductCode30_ENUM_9:
    		return 9		
        case ProductCode30_ENUM_10:
    		return 10		
        case ProductCode30_ENUM_11:
    		return 11		
        case ProductCode30_ENUM_12:
    		return 12		
        case ProductCode30_ENUM_13:
    		return 13		
        default:
        	return 0
    }
}

/**
 * Converts ProductCode30Enum Array to its string Array representation
*/
func ProductCode30EnumArrayToValue(productCode30Enum []ProductCode30Enum) []int {
    convArray := make([]int,len( productCode30Enum))
    for i:=0; i<len(productCode30Enum);i++ {
        convArray[i] = ProductCode30EnumToValue(productCode30Enum[i])
    }
    return convArray
}


/**
 * Converts given value to its enum representation
 */
func ProductCode30EnumFromValue(value int) ProductCode30Enum {
    switch value {
        case 0:
            return ProductCode30_ALL
        case 1:
            return ProductCode30_ENUM_1
        case 2:
            return ProductCode30_ENUM_2
        case 3:
            return ProductCode30_ENUM_3
        case 4:
            return ProductCode30_ENUM_4
        case 5:
            return ProductCode30_TRANSCRIPTION
        case 6:
            return ProductCode30_EMAIL
        case 7:
            return ProductCode30_CONFERENCE
        case 8:
            return ProductCode30_CARRIER
        case 9:
            return ProductCode30_ENUM_9
        case 10:
            return ProductCode30_ENUM_10
        case 11:
            return ProductCode30_ENUM_11
        case 12:
            return ProductCode30_ENUM_12
        case 13:
            return ProductCode30_ENUM_13
        default:
            return ProductCode30_ALL
    }
}
