/*
 * ytelapiv3_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package models_pkg

import(
    "encoding/json"
)

/**
 * Type definition for ProductCode27Enum enum
 */
type ProductCode27Enum int

/**
 * Value collection for ProductCode27Enum enum
 */
const (
    ProductCode27_ALL ProductCode27Enum = 0
    ProductCode27_ENUM_1 = 1
    ProductCode27_ENUM_2 = 2
    ProductCode27_ENUM_3 = 3
    ProductCode27_ENUM_4 = 4
    ProductCode27_TRANSCRIPTION = 5
    ProductCode27_EMAIL = 6
    ProductCode27_CONFERENCE = 7
    ProductCode27_CARRIER = 8
    ProductCode27_ENUM_9 = 9
    ProductCode27_ENUM_10 = 10
    ProductCode27_ENUM_11 = 11
    ProductCode27_ENUM_12 = 12
    ProductCode27_ENUM_13 = 13
)

func (r ProductCode27Enum) MarshalJSON() ([]byte, error) { 
    s := ProductCode27EnumToValue(r)
    return json.Marshal(s) 
} 

func (r *ProductCode27Enum) UnmarshalJSON(data []byte) error { 
    var s int 
    json.Unmarshal(data, &s)
    v :=  ProductCode27EnumFromValue(s)
    *r = v 
    return nil 
 } 


/**
 * Converts ProductCode27Enum to its int representation
 */
func ProductCode27EnumToValue(productCode27Enum ProductCode27Enum) int {
    switch productCode27Enum {
        case ProductCode27_ALL:
    		return 0		
        case ProductCode27_ENUM_1:
    		return 1		
        case ProductCode27_ENUM_2:
    		return 2		
        case ProductCode27_ENUM_3:
    		return 3		
        case ProductCode27_ENUM_4:
    		return 4		
        case ProductCode27_TRANSCRIPTION:
    		return 5		
        case ProductCode27_EMAIL:
    		return 6		
        case ProductCode27_CONFERENCE:
    		return 7		
        case ProductCode27_CARRIER:
    		return 8		
        case ProductCode27_ENUM_9:
    		return 9		
        case ProductCode27_ENUM_10:
    		return 10		
        case ProductCode27_ENUM_11:
    		return 11		
        case ProductCode27_ENUM_12:
    		return 12		
        case ProductCode27_ENUM_13:
    		return 13		
        default:
        	return 0
    }
}

/**
 * Converts ProductCode27Enum Array to its string Array representation
*/
func ProductCode27EnumArrayToValue(productCode27Enum []ProductCode27Enum) []int {
    convArray := make([]int,len( productCode27Enum))
    for i:=0; i<len(productCode27Enum);i++ {
        convArray[i] = ProductCode27EnumToValue(productCode27Enum[i])
    }
    return convArray
}


/**
 * Converts given value to its enum representation
 */
func ProductCode27EnumFromValue(value int) ProductCode27Enum {
    switch value {
        case 0:
            return ProductCode27_ALL
        case 1:
            return ProductCode27_ENUM_1
        case 2:
            return ProductCode27_ENUM_2
        case 3:
            return ProductCode27_ENUM_3
        case 4:
            return ProductCode27_ENUM_4
        case 5:
            return ProductCode27_TRANSCRIPTION
        case 6:
            return ProductCode27_EMAIL
        case 7:
            return ProductCode27_CONFERENCE
        case 8:
            return ProductCode27_CARRIER
        case 9:
            return ProductCode27_ENUM_9
        case 10:
            return ProductCode27_ENUM_10
        case 11:
            return ProductCode27_ENUM_11
        case 12:
            return ProductCode27_ENUM_12
        case 13:
            return ProductCode27_ENUM_13
        default:
            return ProductCode27_ALL
    }
}
