/*
 * ytelapiv3_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package models_pkg

import(
    "encoding/json"
)

/**
 * Type definition for Status24Enum enum
 */
type Status24Enum int

/**
 * Value collection for Status24Enum enum
 */
const (
    Status24_CANCELED Status24Enum = 1 + iota
    Status24_COMPLETED
)

func (r Status24Enum) MarshalJSON() ([]byte, error) { 
    s := Status24EnumToValue(r)
    return json.Marshal(s) 
} 

func (r *Status24Enum) UnmarshalJSON(data []byte) error { 
    var s string 
    json.Unmarshal(data, &s)
    v :=  Status24EnumFromValue(s)
    *r = v 
    return nil 
 } 


/**
 * Converts Status24Enum to its string representation
 */
func Status24EnumToValue(status24Enum Status24Enum) string {
    switch status24Enum {
        case Status24_CANCELED:
    		return "CANCELED"		
        case Status24_COMPLETED:
    		return "COMPLETED"		
        default:
        	return "CANCELED"
    }
}

/**
 * Converts Status24Enum Array to its string Array representation
*/
func Status24EnumArrayToValue(status24Enum []Status24Enum) []string {
    convArray := make([]string,len( status24Enum))
    for i:=0; i<len(status24Enum);i++ {
        convArray[i] = Status24EnumToValue(status24Enum[i])
    }
    return convArray
}


/**
 * Converts given value to its enum representation
 */
func Status24EnumFromValue(value string) Status24Enum {
    switch value {
        case "CANCELED":
            return Status24_CANCELED
        case "COMPLETED":
            return Status24_COMPLETED
        default:
            return Status24_CANCELED
    }
}
