/*
 * ytelapiv3_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package areamail_pkg

import "ytelapiv3_lib/configuration_pkg"

/*
 * Interface for the AREAMAIL_IMPL
 */
type AREAMAIL interface {
    CreateDeleteAreaMail (string) (string, error)

    CreateViewAreaMail (string) (string, error)

    CreateListAreaMails (*int64, *int64, *string, *string) (string, error)

    CreateAreaMail (string, string, string, string, *string, *string, *string) (string, error)
}

/*
 * Factory for the AREAMAIL interaface returning AREAMAIL_IMPL
 */
func NewAREAMAIL(config configuration_pkg.CONFIGURATION) *AREAMAIL_IMPL {
    client := new(AREAMAIL_IMPL)
    client.config = config
    return client
}