/*
 * ytelapiv3_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package conference_pkg

import "ytelapiv3_lib/models_pkg"
import "ytelapiv3_lib/configuration_pkg"

/*
 * Interface for the CONFERENCE_IMPL
 */
type CONFERENCE interface {
    CreatePlayAudio (string, string, models_pkg.AudioUrlEnum) (string, error)

    CreateHangupParticipant (string, string) (string, error)

    CreateViewConference (string) (string, error)

    CreateViewParticipant (string, string) (string, error)

    CreateSilenceParticipant (string, string, *bool, *bool) (string, error)

    AddParticipant (string, string, *bool, *bool) (string, error)

    CreateConference (string, string, string, *string, *string, *string, *string, *string, *bool, *string, *string, *string, *int64) (string, error)

    CreateListParticipants (string, *int64, *int64, *bool, *bool) (string, error)

    CreateListConferences (*int64, *int64, *string, *string) (string, error)
}

/*
 * Factory for the CONFERENCE interaface returning CONFERENCE_IMPL
 */
func NewCONFERENCE(config configuration_pkg.CONFIGURATION) *CONFERENCE_IMPL {
    client := new(CONFERENCE_IMPL)
    client.config = config
    return client
}