/*
 * ytelapiv3_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package YtelAPIV3Client

import(
	"ytelapiv3_lib/configuration_pkg"
	"ytelapiv3_lib/shortcode_pkg"
	"ytelapiv3_lib/areamail_pkg"
	"ytelapiv3_lib/postcard_pkg"
	"ytelapiv3_lib/letter_pkg"
	"ytelapiv3_lib/call_pkg"
	"ytelapiv3_lib/phonenumber_pkg"
	"ytelapiv3_lib/sms_pkg"
	"ytelapiv3_lib/sharedshortcode_pkg"
	"ytelapiv3_lib/conference_pkg"
	"ytelapiv3_lib/carrier_pkg"
	"ytelapiv3_lib/email_pkg"
	"ytelapiv3_lib/account_pkg"
	"ytelapiv3_lib/subaccount_pkg"
	"ytelapiv3_lib/address_pkg"
	"ytelapiv3_lib/recording_pkg"
	"ytelapiv3_lib/transcription_pkg"
	"ytelapiv3_lib/usage_pkg"
)
/*
 * Client structure as interface implementation
 */
type YTELAPIV3_IMPL struct {
     shortcode shortcode_pkg.SHORTCODE
     areamail areamail_pkg.AREAMAIL
     postcard postcard_pkg.POSTCARD
     letter letter_pkg.LETTER
     call call_pkg.CALL
     phonenumber phonenumber_pkg.PHONENUMBER
     sms sms_pkg.SMS
     sharedshortcode sharedshortcode_pkg.SHAREDSHORTCODE
     conference conference_pkg.CONFERENCE
     carrier carrier_pkg.CARRIER
     email email_pkg.EMAIL
     account account_pkg.ACCOUNT
     subaccount subaccount_pkg.SUBACCOUNT
     address address_pkg.ADDRESS
     recording recording_pkg.RECORDING
     transcription transcription_pkg.TRANSCRIPTION
     usage usage_pkg.USAGE
     config  configuration_pkg.CONFIGURATION
}

/**
     * Access to Configuration
     * @return Returns the Configuration instance
*/
func (me *YTELAPIV3_IMPL) Configuration() configuration_pkg.CONFIGURATION {
    return me.config
}
/**
     * Access to ShortCode controller
     * @return Returns the ShortCode() instance
*/
func (me * YTELAPIV3_IMPL) ShortCode() shortcode_pkg.SHORTCODE {
    if(me.shortcode) == nil {
        me.shortcode = shortcode_pkg.NewSHORTCODE(me.config)
    }
    return me.shortcode
}
/**
     * Access to AreaMail controller
     * @return Returns the AreaMail() instance
*/
func (me * YTELAPIV3_IMPL) AreaMail() areamail_pkg.AREAMAIL {
    if(me.areamail) == nil {
        me.areamail = areamail_pkg.NewAREAMAIL(me.config)
    }
    return me.areamail
}
/**
     * Access to PostCard controller
     * @return Returns the PostCard() instance
*/
func (me * YTELAPIV3_IMPL) PostCard() postcard_pkg.POSTCARD {
    if(me.postcard) == nil {
        me.postcard = postcard_pkg.NewPOSTCARD(me.config)
    }
    return me.postcard
}
/**
     * Access to Letter controller
     * @return Returns the Letter() instance
*/
func (me * YTELAPIV3_IMPL) Letter() letter_pkg.LETTER {
    if(me.letter) == nil {
        me.letter = letter_pkg.NewLETTER(me.config)
    }
    return me.letter
}
/**
     * Access to Call controller
     * @return Returns the Call() instance
*/
func (me * YTELAPIV3_IMPL) Call() call_pkg.CALL {
    if(me.call) == nil {
        me.call = call_pkg.NewCALL(me.config)
    }
    return me.call
}
/**
     * Access to PhoneNumber controller
     * @return Returns the PhoneNumber() instance
*/
func (me * YTELAPIV3_IMPL) PhoneNumber() phonenumber_pkg.PHONENUMBER {
    if(me.phonenumber) == nil {
        me.phonenumber = phonenumber_pkg.NewPHONENUMBER(me.config)
    }
    return me.phonenumber
}
/**
     * Access to SMS controller
     * @return Returns the SMS() instance
*/
func (me * YTELAPIV3_IMPL) SMS() sms_pkg.SMS {
    if(me.sms) == nil {
        me.sms = sms_pkg.NewSMS(me.config)
    }
    return me.sms
}
/**
     * Access to SharedShortCode controller
     * @return Returns the SharedShortCode() instance
*/
func (me * YTELAPIV3_IMPL) SharedShortCode() sharedshortcode_pkg.SHAREDSHORTCODE {
    if(me.sharedshortcode) == nil {
        me.sharedshortcode = sharedshortcode_pkg.NewSHAREDSHORTCODE(me.config)
    }
    return me.sharedshortcode
}
/**
     * Access to Conference controller
     * @return Returns the Conference() instance
*/
func (me * YTELAPIV3_IMPL) Conference() conference_pkg.CONFERENCE {
    if(me.conference) == nil {
        me.conference = conference_pkg.NewCONFERENCE(me.config)
    }
    return me.conference
}
/**
     * Access to Carrier controller
     * @return Returns the Carrier() instance
*/
func (me * YTELAPIV3_IMPL) Carrier() carrier_pkg.CARRIER {
    if(me.carrier) == nil {
        me.carrier = carrier_pkg.NewCARRIER(me.config)
    }
    return me.carrier
}
/**
     * Access to Email controller
     * @return Returns the Email() instance
*/
func (me * YTELAPIV3_IMPL) Email() email_pkg.EMAIL {
    if(me.email) == nil {
        me.email = email_pkg.NewEMAIL(me.config)
    }
    return me.email
}
/**
     * Access to Account controller
     * @return Returns the Account() instance
*/
func (me * YTELAPIV3_IMPL) Account() account_pkg.ACCOUNT {
    if(me.account) == nil {
        me.account = account_pkg.NewACCOUNT(me.config)
    }
    return me.account
}
/**
     * Access to SubAccount controller
     * @return Returns the SubAccount() instance
*/
func (me * YTELAPIV3_IMPL) SubAccount() subaccount_pkg.SUBACCOUNT {
    if(me.subaccount) == nil {
        me.subaccount = subaccount_pkg.NewSUBACCOUNT(me.config)
    }
    return me.subaccount
}
/**
     * Access to Address controller
     * @return Returns the Address() instance
*/
func (me * YTELAPIV3_IMPL) Address() address_pkg.ADDRESS {
    if(me.address) == nil {
        me.address = address_pkg.NewADDRESS(me.config)
    }
    return me.address
}
/**
     * Access to Recording controller
     * @return Returns the Recording() instance
*/
func (me * YTELAPIV3_IMPL) Recording() recording_pkg.RECORDING {
    if(me.recording) == nil {
        me.recording = recording_pkg.NewRECORDING(me.config)
    }
    return me.recording
}
/**
     * Access to Transcription controller
     * @return Returns the Transcription() instance
*/
func (me * YTELAPIV3_IMPL) Transcription() transcription_pkg.TRANSCRIPTION {
    if(me.transcription) == nil {
        me.transcription = transcription_pkg.NewTRANSCRIPTION(me.config)
    }
    return me.transcription
}
/**
     * Access to Usage controller
     * @return Returns the Usage() instance
*/
func (me * YTELAPIV3_IMPL) Usage() usage_pkg.USAGE {
    if(me.usage) == nil {
        me.usage = usage_pkg.NewUSAGE(me.config)
    }
    return me.usage
}
