/*
 * ytelapiv3_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package recording_pkg

import "ytelapiv3_lib/configuration_pkg"

/*
 * Interface for the RECORDING_IMPL
 */
type RECORDING interface {
    CreateDeleteRecording (string) (string, error)

    CreateViewRecording (string) (string, error)

    CreateListRecordings (*int64, *int64, *string, *string) (string, error)
}

/*
 * Factory for the RECORDING interaface returning RECORDING_IMPL
 */
func NewRECORDING(config configuration_pkg.CONFIGURATION) *RECORDING_IMPL {
    client := new(RECORDING_IMPL)
    client.config = config
    return client
}