/*
 * ytelapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

package phonenumber_pkg

import "ytelapi_lib/configuration_pkg"

/*
 * Interface for the PHONENUMBER_IMPL
 */
type PHONENUMBER interface {
    CreateIncomingphoneGetdidscore (string) (string, error)

    CreateIncomingphoneBulkbuy (*CreateIncomingphoneBulkbuyInput) (string, error)

    CreateIncomingphoneListnumber (*CreateIncomingphoneListnumberInput) (string, error)

    CreateIncomingphoneBuynumber (string) (string, error)

    CreateIncomingphoneReleasenumberByResponseTypePost (*CreateIncomingphoneReleasenumberByResponseTypePostInput) (string, error)

    CreateIncomingphoneViewnumber (string) (string, error)

    CreateIncomingphoneTransferphonenumbers (*CreateIncomingphoneTransferphonenumbersInput) (string, error)

    CreateIncomingphoneMassreleasenumber (string) (string, error)

    CreateIncomingphoneMassupdatenumber (*CreateIncomingphoneMassupdatenumberInput) (string, error)

    CreateIncomingphoneUpdatenumber (*CreateIncomingphoneUpdatenumberInput) (string, error)

    CreateIncomingphoneAvailablenumber (*CreateIncomingphoneAvailablenumberInput) (string, error)
}

/*
 * Factory for the PHONENUMBER interaface returning PHONENUMBER_IMPL
 */
func NewPHONENUMBER(config configuration_pkg.CONFIGURATION) *PHONENUMBER_IMPL {
    client := new(PHONENUMBER_IMPL)
    client.config = config
    return client
}