/*
 * ytelapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
package models_pkg

import(
    "encoding/json"
)

/**
 * Type definition for ActivateEnum enum
 */
type ActivateEnum int

/**
 * Value collection for ActivateEnum enum
 */
const (
    Activate_MACTIVATE ActivateEnum = 1
    Activate_DEACTIVATE = 0
)

func (r ActivateEnum) MarshalJSON() ([]byte, error) { 
    s := ActivateEnumToValue(r)
    return json.Marshal(s) 
} 

func (r *ActivateEnum) UnmarshalJSON(data []byte) error { 
    var s int 
    json.Unmarshal(data, &s)
    v :=  ActivateEnumFromValue(s)
    *r = v 
    return nil 
 } 


/**
 * Converts ActivateEnum to its int representation
 */
func ActivateEnumToValue(activateEnum ActivateEnum) int {
    switch activateEnum {
        case Activate_MACTIVATE:
    		return 1		
        case Activate_DEACTIVATE:
    		return 0		
        default:
        	return 1
    }
}

/**
 * Converts ActivateEnum Array to its string Array representation
*/
func ActivateEnumArrayToValue(activateEnum []ActivateEnum) []int {
    convArray := make([]int,len( activateEnum))
    for i:=0; i<len(activateEnum);i++ {
        convArray[i] = ActivateEnumToValue(activateEnum[i])
    }
    return convArray
}


/**
 * Converts given value to its enum representation
 */
func ActivateEnumFromValue(value int) ActivateEnum {
    switch value {
        case 1:
            return Activate_MACTIVATE
        case 0:
            return Activate_DEACTIVATE
        default:
            return Activate_MACTIVATE
    }
}
