/*
 * ytelapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
package models_pkg

import(
    "encoding/json"
)

/**
 * Type definition for MergeNumberEnum enum
 */
type MergeNumberEnum int

/**
 * Value collection for MergeNumberEnum enum
 */
const (
    MergeNumber_DELETE MergeNumberEnum = 0
    MergeNumber_MERGE = 1
)

func (r MergeNumberEnum) MarshalJSON() ([]byte, error) { 
    s := MergeNumberEnumToValue(r)
    return json.Marshal(s) 
} 

func (r *MergeNumberEnum) UnmarshalJSON(data []byte) error { 
    var s int 
    json.Unmarshal(data, &s)
    v :=  MergeNumberEnumFromValue(s)
    *r = v 
    return nil 
 } 


/**
 * Converts MergeNumberEnum to its int representation
 */
func MergeNumberEnumToValue(mergeNumberEnum MergeNumberEnum) int {
    switch mergeNumberEnum {
        case MergeNumber_DELETE:
    		return 0		
        case MergeNumber_MERGE:
    		return 1		
        default:
        	return 0
    }
}

/**
 * Converts MergeNumberEnum Array to its string Array representation
*/
func MergeNumberEnumArrayToValue(mergeNumberEnum []MergeNumberEnum) []int {
    convArray := make([]int,len( mergeNumberEnum))
    for i:=0; i<len(mergeNumberEnum);i++ {
        convArray[i] = MergeNumberEnumToValue(mergeNumberEnum[i])
    }
    return convArray
}


/**
 * Converts given value to its enum representation
 */
func MergeNumberEnumFromValue(value int) MergeNumberEnum {
    switch value {
        case 0:
            return MergeNumber_DELETE
        case 1:
            return MergeNumber_MERGE
        default:
            return MergeNumber_DELETE
    }
}
