/*
 * ytelapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

package models_pkg



/*
 * Structure for the custom type Error
 */
type Error struct {
    Code            string          `json:"Code" form:"Code"` //Error Response Code
    Message         string          `json:"Message" form:"Message"` //Error Response Message
    MoreInfo        []string        `json:"MoreInfo" form:"MoreInfo"` //Detailed Error Info
}

/*
 * Structure for the custom type Errors
 */
type Errors struct {
    Error           []*Error        `json:"Error" form:"Error"` //Error Description
}
