/*
 * ytelapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
package models_pkg

import(
    "encoding/json"
)

/**
 * Type definition for ProductCodeEnum enum
 */
type ProductCodeEnum int

/**
 * Value collection for ProductCodeEnum enum
 */
const (
    ProductCode_ALL ProductCodeEnum = 0
    ProductCode_ENUM_1 = 1
    ProductCode_ENUM_2 = 2
    ProductCode_ENUM_3 = 3
    ProductCode_ENUM_4 = 4
    ProductCode_TRANSCRIPTION = 5
    ProductCode_EMAIL = 6
    ProductCode_CONFERENCE = 7
    ProductCode_CARRIER = 8
    ProductCode_ENUM_9 = 9
    ProductCode_ENUM_10 = 10
    ProductCode_ENUM_11 = 11
    ProductCode_ENUM_12 = 12
    ProductCode_ENUM_13 = 13
)

func (r ProductCodeEnum) MarshalJSON() ([]byte, error) { 
    s := ProductCodeEnumToValue(r)
    return json.Marshal(s) 
} 

func (r *ProductCodeEnum) UnmarshalJSON(data []byte) error { 
    var s int 
    json.Unmarshal(data, &s)
    v :=  ProductCodeEnumFromValue(s)
    *r = v 
    return nil 
 } 


/**
 * Converts ProductCodeEnum to its int representation
 */
func ProductCodeEnumToValue(productCodeEnum ProductCodeEnum) int {
    switch productCodeEnum {
        case ProductCode_ALL:
    		return 0		
        case ProductCode_ENUM_1:
    		return 1		
        case ProductCode_ENUM_2:
    		return 2		
        case ProductCode_ENUM_3:
    		return 3		
        case ProductCode_ENUM_4:
    		return 4		
        case ProductCode_TRANSCRIPTION:
    		return 5		
        case ProductCode_EMAIL:
    		return 6		
        case ProductCode_CONFERENCE:
    		return 7		
        case ProductCode_CARRIER:
    		return 8		
        case ProductCode_ENUM_9:
    		return 9		
        case ProductCode_ENUM_10:
    		return 10		
        case ProductCode_ENUM_11:
    		return 11		
        case ProductCode_ENUM_12:
    		return 12		
        case ProductCode_ENUM_13:
    		return 13		
        default:
        	return 0
    }
}

/**
 * Converts ProductCodeEnum Array to its string Array representation
*/
func ProductCodeEnumArrayToValue(productCodeEnum []ProductCodeEnum) []int {
    convArray := make([]int,len( productCodeEnum))
    for i:=0; i<len(productCodeEnum);i++ {
        convArray[i] = ProductCodeEnumToValue(productCodeEnum[i])
    }
    return convArray
}


/**
 * Converts given value to its enum representation
 */
func ProductCodeEnumFromValue(value int) ProductCodeEnum {
    switch value {
        case 0:
            return ProductCode_ALL
        case 1:
            return ProductCode_ENUM_1
        case 2:
            return ProductCode_ENUM_2
        case 3:
            return ProductCode_ENUM_3
        case 4:
            return ProductCode_ENUM_4
        case 5:
            return ProductCode_TRANSCRIPTION
        case 6:
            return ProductCode_EMAIL
        case 7:
            return ProductCode_CONFERENCE
        case 8:
            return ProductCode_CARRIER
        case 9:
            return ProductCode_ENUM_9
        case 10:
            return ProductCode_ENUM_10
        case 11:
            return ProductCode_ENUM_11
        case 12:
            return ProductCode_ENUM_12
        case 13:
            return ProductCode_ENUM_13
        default:
            return ProductCode_ALL
    }
}
