/*
 * ytelapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

package shortcode_pkg

import "ytelapi_lib/configuration_pkg"

/*
 * Interface for the SHORTCODE_IMPL
 */
type SHORTCODE interface {
    CreateDedicatedshortcodeListshortcode (*CreateDedicatedshortcodeListshortcodeInput) (string, error)

    CreateDedicatedshortcodeUpdateshortcode (*CreateDedicatedshortcodeUpdateshortcodeInput) (string, error)

    CreateDedicatedshortcodeViewshortcode (string) (string, error)

    CreateShortcodeViewsms (string) (string, error)

    CreateDedicatedshortcodeGetinboundsms (*CreateDedicatedshortcodeGetinboundsmsInput) (string, error)

    CreateDedicatedshortcodeSendsms (*CreateDedicatedshortcodeSendsmsInput) (string, error)

    CreateShortcodeListsms (*CreateShortcodeListsmsInput) (string, error)
}

/*
 * Factory for the SHORTCODE interaface returning SHORTCODE_IMPL
 */
func NewSHORTCODE(config configuration_pkg.CONFIGURATION) *SHORTCODE_IMPL {
    client := new(SHORTCODE_IMPL)
    client.config = config
    return client
}