/*
 * ytelapiv3_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package sms_pkg

import "ytelapiv3_lib/configuration_pkg"

/*
 * Interface for the SMS_IMPL
 */
type SMS interface {
    CreateViewSMS1 (string) (string, error)

    CreateViewSMS (string) (string, error)

    CreateSendSMS (string, string, string, *string, *string, *bool, *bool) (string, error)

    CreateListSMS (*int64, *int64, *string, *string, *string) (string, error)

    CreateListInboundSMS (*int64, *int64, *string, *string, *string) (string, error)
}

/*
 * Factory for the SMS interaface returning SMS_IMPL
 */
func NewSMS(config configuration_pkg.CONFIGURATION) *SMS_IMPL {
    client := new(SMS_IMPL)
    client.config = config
    return client
}