/*
 * ytelapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

package postcard_pkg

import "ytelapi_lib/configuration_pkg"

/*
 * Interface for the POSTCARD_IMPL
 */
type POSTCARD interface {
    PostcardDeletepostcard (string) (string, error)

    PostcardViewpostcard (string) (string, error)

    PostcardListpostcard (*PostcardListpostcardInput) (string, error)

    PostcardCreatepostcard (*PostcardCreatepostcardInput) (string, error)
}

/*
 * Factory for the POSTCARD interaface returning POSTCARD_IMPL
 */
func NewPOSTCARD(config configuration_pkg.CONFIGURATION) *POSTCARD_IMPL {
    client := new(POSTCARD_IMPL)
    client.config = config
    return client
}