/*
 * ytelapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

package sharedshortcode_pkg

import "github.com/satori/go.uuid"
import "ytelapi_lib/configuration_pkg"

/*
 * Interface for the SHAREDSHORTCODE_IMPL
 */
type SHAREDSHORTCODE interface {
    CreateShortcodeViewshortcode (string) (string, error)

    CreateKeywordView (string) (string, error)

    CreateShortcodeUpdateshortcode (*CreateShortcodeUpdateshortcodeInput) (string, error)

    CreateTemplateView (uuid.UUID) (string, error)

    CreateShortcodeListshortcode (*CreateShortcodeListshortcodeInput) (string, error)

    CreateKeywordLists (*CreateKeywordListsInput) (string, error)

    CreateTemplateLists (*CreateTemplateListsInput) (string, error)

    CreateShortcodeSendsms (*CreateShortcodeSendsmsInput) (string, error)

    CreateShortcodeGetinboundsms (*CreateShortcodeGetinboundsmsInput) (string, error)
}

/*
 * Factory for the SHAREDSHORTCODE interaface returning SHAREDSHORTCODE_IMPL
 */
func NewSHAREDSHORTCODE(config configuration_pkg.CONFIGURATION) *SHAREDSHORTCODE_IMPL {
    client := new(SHAREDSHORTCODE_IMPL)
    client.config = config
    return client
}