/*
 * ytelapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

package sms_pkg

import "ytelapi_lib/configuration_pkg"

/*
 * Interface for the SMS_IMPL
 */
type SMS interface {
    CreateSmsViewdetailsms (string) (string, error)

    CreateSmsViewsms (string) (string, error)

    CreateSmsGetinboundsms (*CreateSmsGetinboundsmsInput) (string, error)

    CreateSmsListsms (*CreateSmsListsmsInput) (string, error)

    CreateSmsSendsms (*CreateSmsSendsmsInput) (string, error)
}

/*
 * Factory for the SMS interaface returning SMS_IMPL
 */
func NewSMS(config configuration_pkg.CONFIGURATION) *SMS_IMPL {
    client := new(SMS_IMPL)
    client.config = config
    return client
}