/*
 * ytelapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

package areamail_pkg

import "ytelapi_lib/configuration_pkg"

/*
 * Interface for the AREAMAIL_IMPL
 */
type AREAMAIL interface {
    CreateAreamailDelete (string) (string, error)

    CreateAreamailCreate (*CreateAreamailCreateInput) (string, error)

    CreateAreamailView (string) (string, error)

    CreateAreamailLists (*CreateAreamailListsInput) (string, error)
}

/*
 * Factory for the AREAMAIL interaface returning AREAMAIL_IMPL
 */
func NewAREAMAIL(config configuration_pkg.CONFIGURATION) *AREAMAIL_IMPL {
    client := new(AREAMAIL_IMPL)
    client.config = config
    return client
}